
use red_social_dev;

INSERT INTO usuario (nombreUsuario) VALUES ('JUAN');
INSERT INTO usuario (nombreUsuario) VALUES ('DARIO');
INSERT INTO usuario (nombreUsuario) VALUES ('ANA');
INSERT INTO usuario (nombreUsuario) VALUES ('MARIA');
INSERT INTO usuario (nombreUsuario) VALUES ('SEBASTIAN');
INSERT INTO usuario (nombreUsuario) VALUES ('ALEXANDER');
INSERT INTO usuario (nombreUsuario) VALUES ('CAMILA');
INSERT INTO usuario (nombreUsuario) VALUES ('KAREN');
INSERT INTO usuario (nombreUsuario) VALUES ('CARLOS');
INSERT INTO usuario (nombreUsuario) VALUES ('ALBERTO');
INSERT INTO usuario (nombreUsuario) VALUES ('XIMENA');
INSERT INTO usuario (nombreUsuario) VALUES ('SANDRA');
INSERT INTO usuario (nombreUsuario) VALUES ('OLIVAR');
INSERT INTO usuario (nombreUsuario) VALUES ('MARK');
INSERT INTO usuario (nombreUsuario) VALUES ('ANDRES');
INSERT INTO usuario (nombreUsuario) VALUES ('BAIRON');
INSERT INTO usuario (nombreUsuario) VALUES ('ALEJANDRA');
INSERT INTO usuario (nombreUsuario) VALUES ('MAYERLI');
INSERT INTO usuario (nombreUsuario) VALUES ('VIVIANA');
INSERT INTO usuario (nombreUsuario) VALUES ('DAYANI');
INSERT INTO usuario (nombreUsuario) VALUES ('RUBY');
INSERT INTO usuario (nombreUsuario) VALUES ('ISABEL');
INSERT INTO usuario (nombreUsuario) VALUES ('ANGELA');
INSERT INTO usuario (nombreUsuario) VALUES ('JOSE');
INSERT INTO usuario (nombreUsuario) VALUES ('ARTURO');
INSERT INTO usuario (nombreUsuario) VALUES ('FELIPE');
INSERT INTO usuario (nombreUsuario) VALUES ('YAISON');
